name: devopsProject
on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Code Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Java 17
      - name: Set Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Setup SonarQube Scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Step 4: Run SonarQube Scan
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=$GITHUB_WORKSPACE
